image: node:18

stages:
  - build
  - deploy

before_script:
  - npm install

# Build stage: React 앱 빌드
build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build

# Deploy stage: GitLab Pages에 배포
deploy:
  stage: deploy
  script:
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public  # 'build' 디렉터리를 'public' 디렉터리로 이름 변경
  artifacts:
    paths:
      - public  # 'public' 디렉터리 내의 파일을 GitLab Pages에 배포
  only:
    - main

# GitLab Pages 설정
pages:
  stage: deploy
  script:
    - mv build public  # 'build' 디렉터리를 'public' 디렉터리로 이름 변경
  artifacts:
    paths:
      - public  # public 폴더를 GitLab Pages에 배포
  only:
    - main