name: Deploy Homepage React App

on:
  push:
    branches:
      - dev # dev브랜치에 푸쉬가 일어나면 실행되도록 설정

jobs:
  deploy:
    runs-on: ubuntu-latest  # 작업환경 : ubuntu 최신버전

    steps:
      # Build 전 pre-code-check (코드 검사)
      - name: Checkout code
        uses: actions/checkout@v3

      # dependencies를 설치
      - name: Install dependencies
        run: sudo yarn install

      # React App 빌드
      - name: React App Build
        run: sudo yarn build

      # ubuntu 서버에 접속하여 빌드파일을 전송하고 배포된 파일을 교체
      - name: Copy build directory to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.WWW_SERVER_HOST }}
          username: ${{ secrets.WWW_SERVER_USER }}
          password: ${{ secrets.WWW_SERVER_PASSWORD }}
          port: ${{ secrets.WWW_SERVER_PORT }}
          source: "./build/"
          target: "/home/deploy/www_dev"

      # ubuntu서버에 접속하여 docker-compose를 내렸다가 다시 올린다.
      - name: Docker-compose down and up as node server restart
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.WWW_SERVER_HOST }}
          username: ${{ secrets.WWW_SERVER_USER }}
          password: ${{ secrets.WWW_SERVER_PASSWORD }}
          port: ${{ secrets.WWW_SERVER_PORT }}
          script: |
            cd /home/deploy/www_dev
            docker-compose down
            docker-compose up -d
